# Generated by Django 5.1.3 on 2024-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PapersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to='static\\Files')),
            ],
            options={
                'db_table': 'PapersModel',
            },
        ),
    ]
